name: MERN DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:

  security-build-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      # Backend Dependency Check
      - name: Install Backend Dependencies
        working-directory: Application-Code/backend
        run: npm install


      # Frontend Dependency Check
      - name: Install Frontend Dependencies
        working-directory: Application-Code/frontend
        run: npm install


      # Trivy Security Scan
      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .


      # Configure AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1


      # Verify AWS
      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      # Login Docker to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login \
          --username AWS \
          --password-stdin 943938400079.dkr.ecr.ap-south-1.amazonaws.com


      # Verify ECR Registry
      - name: Verify ECR Registry
        run: |
          echo "Backend Registry:"
          echo "${{ secrets.ECR_BACKEND_URL }}" | cut -d'/' -f1


      # Build Backend Image
      - name: Build Backend Image
        run: |
          docker build \
          -t mern-backend \
          ./Application-Code/backend


      # Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker build \
          -t mern-frontend \
          ./Application-Code/frontend


      # Push Images to ECR
      - name: Push Images to ECR
        run: |

          docker tag mern-backend:latest \
          ${{ secrets.ECR_BACKEND_URL }}:latest

          docker tag mern-frontend:latest \
          ${{ secrets.ECR_FRONTEND_URL }}:latest


          docker push \
          ${{ secrets.ECR_BACKEND_URL }}:latest

          docker push \
          ${{ secrets.ECR_FRONTEND_URL }}:latest


      # Configure EKS Access
      - name: Configure kubectl for EKS
        run: |
          aws eks update-kubeconfig \
          --region ap-south-1 \
          --name mern-eks-cluster


      # Deploy Latest Images
      - name: Update Kubernetes Deployment
        run: |

          kubectl set image deployment/backend \
          backend=${{ secrets.ECR_BACKEND_URL }}:latest


          kubectl set image deployment/frontend \
          frontend=${{ secrets.ECR_FRONTEND_URL }}:latest


      # Verify Deployment
      - name: Verify Kubernetes Rollout
        run: |

          kubectl rollout status deployment/backend

          kubectl rollout status deployment/frontend